//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadScienceAdo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_asignacion
    {
        public int id_asignacion { get; set; }
        public int id_detalle { get; set; }
        public int id_trabajador { get; set; }
        public int id_tipo_pago { get; set; }
        public double monto { get; set; }
        public System.DateTime fch_reserva { get; set; }
        public System.DateTime fch_creacion { get; set; }
        public string user_crea { get; set; }
        public double horaInicio { get; set; }
        public double horaFin { get; set; }
        public int id_reserva { get; set; }
    
        public virtual tb_detalle_reserva tb_detalle_reserva { get; set; }
        public virtual tb_tipo_pago tb_tipo_pago { get; set; }
        public virtual tb_trabajador tb_trabajador { get; set; }
        public virtual tb_reserva tb_reserva { get; set; }
    }
}
