//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadScienceAdo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_disponibilidad
    {
        public int id_horario { get; set; }
        public int id_trabajador { get; set; }
        public System.DateTime fch_creacion { get; set; }
        public string usr_creacion { get; set; }
    
        public virtual tb_horario tb_horario { get; set; }
        public virtual tb_trabajador tb_trabajador { get; set; }
    }
}
