//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadScienceAdo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_detalle_reserva
    {
        public tb_detalle_reserva()
        {
            this.tb_asignacion = new HashSet<tb_asignacion>();
        }
    
        public int id_detalle { get; set; }
        public int id_reserva { get; set; }
        public int id_fiesta { get; set; }
        public System.DateTime fch_creacion { get; set; }
        public string usr_crea { get; set; }
    
        public virtual ICollection<tb_asignacion> tb_asignacion { get; set; }
        public virtual tb_fiesta tb_fiesta { get; set; }
        public virtual tb_reserva tb_reserva { get; set; }
    }
}
