//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadScienceAdo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_fiesta_evento
    {
        public int id_tipo_evento { get; set; }
        public int id_fiesta { get; set; }
        public System.DateTime fch_creacion { get; set; }
    
        public virtual tb_fiesta tb_fiesta { get; set; }
        public virtual tb_tipo_evento tb_tipo_evento { get; set; }
    }
}
