//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadScienceAdo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_horario
    {
        public tb_horario()
        {
            this.tb_disponibilidad = new HashSet<tb_disponibilidad>();
        }
    
        public int id_horario { get; set; }
        public string nomDia { get; set; }
        public Nullable<double> horaInicio { get; set; }
        public Nullable<double> horaFin { get; set; }
    
        public virtual ICollection<tb_disponibilidad> tb_disponibilidad { get; set; }
    }
}
