//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadScienceAdo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_reserva
    {
        public tb_reserva()
        {
            this.tb_detalle_reserva = new HashSet<tb_detalle_reserva>();
            this.tb_asignacion = new HashSet<tb_asignacion>();
        }
    
        public int id_reserva { get; set; }
        public int id_tipo_evento { get; set; }
        public Nullable<int> id_tienda { get; set; }
        public int id_usuario { get; set; }
        public string direccion { get; set; }
        public string nombreNiño { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string telefono { get; set; }
        public string celular { get; set; }
        public string nombreCliente { get; set; }
        public System.DateTime fechaCelebracion { get; set; }
        public double horaInicio { get; set; }
        public double horaFin { get; set; }
        public string modeloTorta { get; set; }
        public string saborTorta { get; set; }
        public string obsTorta2 { get; set; }
        public Nullable<int> invitados { get; set; }
        public string obsGeneral { get; set; }
        public string flg_estado { get; set; }
        public string usr_crea { get; set; }
        public System.DateTime fch_creacion { get; set; }
        public string flg_doble { get; set; }
    
        public virtual ICollection<tb_detalle_reserva> tb_detalle_reserva { get; set; }
        public virtual tb_tienda tb_tienda { get; set; }
        public virtual tb_tipo_evento tb_tipo_evento { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
        public virtual ICollection<tb_asignacion> tb_asignacion { get; set; }
    }
}
