//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadScienceAdo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tipo_fiesta
    {
        public tb_tipo_fiesta()
        {
            this.tb_fiesta = new HashSet<tb_fiesta>();
        }
    
        public int id_tipo_fiesta { get; set; }
        public string nombre { get; set; }
        public string flg_estado { get; set; }
        public System.DateTime fch_creacion { get; set; }
    
        public virtual ICollection<tb_fiesta> tb_fiesta { get; set; }
    }
}
