//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadScienceAdo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tipo_evento
    {
        public tb_tipo_evento()
        {
            this.tb_fiesta_evento = new HashSet<tb_fiesta_evento>();
            this.tb_reserva = new HashSet<tb_reserva>();
        }
    
        public int id_tipo_evento { get; set; }
        public string nombre { get; set; }
        public string flg_estado { get; set; }
    
        public virtual ICollection<tb_fiesta_evento> tb_fiesta_evento { get; set; }
        public virtual ICollection<tb_reserva> tb_reserva { get; set; }
    }
}
