//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadScienceAdo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario
    {
        public tb_usuario()
        {
            this.tb_reserva = new HashSet<tb_reserva>();
        }
    
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string apePat { get; set; }
        public string apeMat { get; set; }
        public string flg_estado { get; set; }
        public string constraseña { get; set; }
        public string login { get; set; }
    
        public virtual ICollection<tb_reserva> tb_reserva { get; set; }
    }
}
