//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MadScienceAdo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_zona
    {
        public tb_zona()
        {
            this.tb_tienda = new HashSet<tb_tienda>();
        }
    
        public int id_zona { get; set; }
        public string nombre { get; set; }
        public string flg_estado { get; set; }
    
        public virtual ICollection<tb_tienda> tb_tienda { get; set; }
    }
}
